// <auto-generated />
namespace _18_ConsoleApp_Entity_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Medicamento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Medicamento));
        
        string IMigrationMetadata.Id
        {
            get { return "202207051827470_Medicamento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
