// <auto-generated />
namespace _18_ConsoleApp_Entity_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PacienteCPF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PacienteCPF));
        
        string IMigrationMetadata.Id
        {
            get { return "202207051818371_PacienteCPF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
