// <auto-generated />
namespace _18_ConsoleApp_Entity_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Medicamento1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Medicamento1));
        
        string IMigrationMetadata.Id
        {
            get { return "202207051836335_Medicamento1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
